title: Shoutem Developers
description: Supercharge your React Native development with Shoutem
tracking_id: UA-807293-5

sass:
  style: compressed

# Build settings
markdown: kramdown

kramdown: 
  syntax_highlighter_opts:
    disable : true

url: "http://shoutem.github.io"

# Variables
shoutem:
  builderURL: "https://builder.beta.shoutem.com"
  mobilizer: "/docs/coming-soon"