title: Shoutem Developers
description: Supercharge your React Native development with Shoutem
tracking_id: UA-807293-5

sass:
  style: compressed

# Build settings
markdown: kramdown

kramdown: 
  syntax_highlighter_opts:
    disable : true

url: "http://shoutem.github.io"
exclude: ['api-src/']

# Variables
shoutem:
  builderURL: "http://builder.beta.shoutem.com"
