title: Shoutem Developers
description: Supercharge your React Native development with Shoutem
tracking_id: UA-807293-5
repository: shoutem/shoutem.github.io

sass:
  style: compressed

# Build settings
markdown: kramdown

kramdown: 
  syntax_highlighter_opts:
    disable : true

url: "http://shoutem.github.io"

# Variables
shoutem:
  builderURL: "https://builder.beta.shoutem.com"
  previewApp: "/docs/coming-soon"
  cli: "https://www.npmjs.com/package/@shoutem/cli"
  school: "http://school.shoutem.com/"

# Examples
example:
  devName: tom
  devEmail: tom@shoutem.com
  appId: 8074
