title: Developer portal
email: tomislav.tenodi@shoutem.com
description: Supercharge your React Native development with Shoutem
baseurl: ""
twitter_username: TomislavTenodi
github_username:  tenodi
tracking_id: UA-807293-5

sass:
  style: compressed

# Build settings
markdown: kramdown

url: "http://shoutem.github.io"